spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: auth-service

  datasource:
    url: ${AUTH_DB_URL}
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

  flyway:
    enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

app:
  jwt:
    secret: ${JWT_SECRET}
    issuer: "auth-service"
    access-token-expiration: 15m
    refresh-token-expiration: 30d

server:
  port: 8081
