version: '3.8'

services:
  auth-db:
    image: postgres:16-alpine
    container_name: postgres_auth
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - microservices-net


  order-db:
    image: postgres:16-alpine
    container_name: postgres_order
    environment:
      POSTGRES_USER: ${ORDER_DB_USER}
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD}
      POSTGRES_DB: orders_db
    ports:
      - "5433:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    networks:
      - microservices-net

  inventory-db:
    image: postgres:16-alpine
    container_name: postgres_inventory
    environment:
      POSTGRES_USER: ${INVENTORY_DB_USER}
      POSTGRES_PASSWORD: ${INVENTORY_DB_PASSWORD}
      POSTGRES_DB: inventory_db
    ports:
      - "5434:5432"
    volumes:
      - inventory_db_data:/var/lib/postgresql/data
    networks:
      - microservices-net

  payment-db:
    image: postgres:16-alpine
    container_name: postgres_payment
    environment:
      POSTGRES_USER: ${PAYMENT_DB_USER}
      POSTGRES_PASSWORD: ${PAYMENT_DB_PASSWORD}
      POSTGRES_DB: payment_db
    ports:
      - "5435:5432"
    volumes:
      - payment_db_data:/var/lib/postgresql/data
    networks:
      - microservices-net

  notification-db:
    image: postgres:16-alpine
    container_name: postgres_notification
    environment:
      POSTGRES_USER: ${NOTIFICATION_DB_USER}
      POSTGRES_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
      POSTGRES_DB: notification_db
    ports:
      - "5436:5432"
    volumes:
      - notification_db_data:/var/lib/postgresql/data
    networks:
      - microservices-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  microservices-net:
    driver: bridge

volumes:
  user_db_data:
  order_db_data:
  inventory_db_data:
  payment_db_data:
  notification_db_data:
  rabbitmq_data:
    driver: local